name: build

on:
  pull_request: { }
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dorg.gradle.daemon=false -Dhttp.keepAlive=false -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.net.http.retryPost=false -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
    - name: Validate Gradle Wrapper
      uses: Wandalen/wretry.action@v1.0.11
      with:
        action: gradle/wrapper-validation-action@v1
        attempt_limit: 3
        attempt_delay: 15000
    - name: Cache Gradle
      uses: remal-github-actions/cache-gradle@main
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Build
      env:
        DATA_REPOSITORY: ${{secrets.DATA_REPOSITORY}}
        DATA_REPOSITORY_BRANCH: ${{secrets.DATA_REPOSITORY_BRANCH}}
        DATA_REPOSITORY_TOKEN: ${{secrets.DATA_REPOSITORY_TOKEN}}
      run: |
        ./gradlew build testRun
    - name: Upload recordings
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: recordings
        path: .recordings/*
        retention-days: 7
