name: build

on:
  pull_request: { }
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dorg.gradle.daemon=false -Dhttp.keepAlive=false -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.net.http.retryPost=false -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Setup Java 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: zulu
    - name: Cache Gradle
      uses: remal-github-actions/cache-gradle@main
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Cache Docker images
      uses: satackey/action-docker-layer-caching@v0.0.11
      with:
        key: ${{runner.os}}-docker-layers-${{hashFiles('**/gradle/wrapper/gradle-wrapper.properties', '**/*.gradle', '**/*.gradle.kts', '**/gradle.properties')}}-v1
        restore-keys: |
          ${{runner.os}}-docker-layers-
    - name: Build
      run: |
        ./gradlew build
