name: run

on:
  push:
    branches:
    - main
  pull_request: { }
  schedule:
  - cron: '29 1 * * *'
  workflow_dispatch: { }

defaults:
  run:
    shell: bash

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=4 -Dorg.gradle.warning.mode=all -Dorg.gradle.daemon=false -Dhttp.keepAlive=false -Dsun.net.client.defaultConnectTimeout=15000 -Dsun.net.client.defaultReadTimeout=600000 -Dsun.net.http.retryPost=false -Dsun.io.useCanonCaches=false -Djava.awt.headless=true -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 1
    - name: Setup Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        cache: gradle
    - name: Run
      env:
        DATA_REPOSITORY: ${{secrets.DATA_REPOSITORY}}
        DATA_REPOSITORY_BRANCH: ${{secrets.DATA_REPOSITORY_BRANCH}}
        DATA_REPOSITORY_TOKEN: ${{secrets.DATA_REPOSITORY_TOKEN}}
      run: |
        ./gradlew run
    - name: Upload recordings
      uses: actions/upload-artifact@v3
      with:
        name: recordings
        path: .recordings/*
        retention-days: 7
